# Generated by Django 4.2 on 2023-05-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_id_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_tab',
        ),
        migrations.AddField(
            model_name='product',
            name='id_tag',
            field=models.CharField(blank=True, default='tag-', max_length=10, null=True),
        ),
    ]
