# Generated by Django 4.2 on 2023-05-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_id_tab_product_id_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='id_tab',
            field=models.CharField(blank=True, default='tab-', max_length=10, null=True),
        ),
    ]
