# Generated by Django 4.2 on 2023-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_id_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_view_link',
            field=models.URLField(default='', max_length=100),
        ),
    ]
