# Generated by Django 4.2 on 2023-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_detail_view_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_view_link',
            field=models.CharField(default="'store:product_detail' category_slug=product.category.slug product_slug=product.slug", max_length=100),
        ),
    ]
